#!/usr/bin/env python

"""Converts a video file to the mpeg2 format, creates the dvd filesytem, burns the dvd. Creates no menus"""

import os, sys, logging, tempfile, datetime, shutil
from optparse import OptionParser

def is_success(status):
	return 0 == status

def process(log, opts, files):
	log.info("Creating a temp directory")
	dvddir = tempfile.mkdtemp("", "makedvd_", opts.tmpdir)
	log.info("Dvd image dir: '" + dvddir + "'")
	status = 0
	for f in files:
		log.info("Converting " + f + " into mpeg2")
		# outfile = tempfile.mkstemp(".mpeg2", "makedvd_", opts.tmpdir)[1]
		outfile = os.path.splitext(os.path.basename(f))[0] + ".vob" #TODO: this is ugly, made movie-to-dvd take -o arg
		tmpdir = tempfile.mkdtemp("", "makedvd_", opts.tmpdir)
		outfile = tmpdir + '/' + outfile
		log.info("Temp file: " + outfile)
# 		convcmd = "mencoder -noskip -of mpeg -mpegopts format=dvd:tsaf:vframerate=25 -srate 48000 -ofps 25 -ovc lavc -oac lavc \
# 		-lavcopts vcodec=mpeg2video:vrc_buf_size=1835:keyint=15:vrc_maxrate=9800:vbitrate=4900:acodec=ac3:abitrate=192 " \
# 		"" + f + " -o " + outfile
		convcmd = 'movie-to-dvd -m pal -M -a 4:3 -o ' + tmpdir + ' ' + f
		log.info("Executing \"" + convcmd + "\"")
		status = os.system(convcmd)
		if not is_success(status):
			log.error("Can't convert " + f + " to mpeg2, status: " + str(status))
		else:
			log.info("Adding the generated mpeg2 file to the dvd filesystem")
			addcmd = "dvdauthor -o " + dvddir + "/ -t " + outfile
			log.info("Executing \"" + addcmd + "\"")
			status = os.system(addcmd)
			if not is_success(status):
				log.error("Can't add a mpeg2 file to dvd")
		log.info("Removing " + tmpdir)
		shutil.rmtree(tmpdir)
#		os.unlink(outfile)
		if not is_success(status):
			log.info('Removing ' + dvddir)
			shutil.rmtree(dvddir)
			return status

	assert(is_success(status))

	log.info("Finalizing the dvd")
	fincmd = "dvdauthor -o " + dvddir + "/ -T"
	log.info("Executing \"" + fincmd + "\"")
	status = os.system(fincmd)
	if not is_success(status):
		log.error("Can't finalize the dvd")
	else:
		dvddev = opts.dvddev
		log.info('Burning the dvd. dvddev: ' + dvddev)
		burncmd = 'growisofs -dvd-compat -Z ' + dvddev + ' -dvd-video -J -R -V \"' + str(datetime.datetime.today()) + '\" ' + dvddir + '/'
		log.info("Executing \"" + burncmd + "\"")
		status = os.system(burncmd)
		if not is_success(status):
			log.error("Can't burn the iso image")
	log.info('Removing ' + dvddir)
	shutil.rmtree(dvddir)
	return status

def main():
	usage = """%prog file [file ...]"""
	parser = OptionParser(usage=usage, version="%prog 1.0")
	parser.add_option("-d", "--dvd-device", dest="dvddev", default='/dev/dvd', help='dvd device')
	parser.add_option("-t", "--tmp-directory", dest="tmpdir", default='/tmp', help='directory for temporary files')

	opts, args = parser.parse_args()
	if len(args) == 0:
		parser.print_help()
		sys.exit(1)

	outformat = '%(name)-12s %(asctime)s    %(levelname)-12s %(message)s'
	dateformat = '%y.%m.%d %H:%M:%S' #TODO: four digit year
	logging.basicConfig(level=logging.DEBUG, format=outformat, datefmt=dateformat)

	scriptname = os.path.basename(sys.argv[0])
	log = logging.getLogger(scriptname)
	log.info(scriptname + ' started')

	status = process(log, opts, args)
	msg = "Successfully made dvd" if is_success(status) else "Can't make dvd"
	log.info(msg + '. Bye')

if __name__ == '__main__':
	main()

